### ISSUE TITLE
setLoop didn't call clearInterval ? 

### ISSUE THREAD

**Issue by alainib** [aswincheriyala/react-native-animated-colors#7]
i use  this package as a skeleton in a Flatlist while loading.

i'm getting this error when i pull to refresh 3/4 times, not sure if this call is correct 

 maybe it need a component umount to stop loop ?

` WARN  Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"170937":{},"170941":{},"170945":{},"170949":{},"170953":{},"170957":{},"170961":{},"170965":{},"170969":{},"170973":{},"170977":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"170981":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"170985":{},"170989":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"170993":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"170997":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171001":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171005":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171008":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171011":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171014":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171017":{},"171020":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171023":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171533":{},"171537":{},"171541":{},"171545":{},"171549":{},"171553":{},"171557":{},"171561":{},"171565":{},"171569":{},"171573":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171577":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171581":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171585":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171589":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171593":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171597":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171601":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"171697":{},"171701":{},"171705":{},"171709":{},"171713":{},"171717":{},"171721":{},"171725":{},"...(truncated keys)...":451}`

**Comment by alainib** [comment]
my lite version with hooks



```
import React, {ReactNode, useEffect, useState} from 'react';
import {View, Animated, StyleSheet} from 'react-native';

type AnimatedColorViewType = {
  loop?: boolean;
  colors?: Array<string>;
  duration?: number;
  children?: ReactNode;
  style?: object;
};

const createValue = (colors: Array<string>) => {
  let av: Array<any> = [];
  colors &&
    colors.map(() => {
      av.push(new Animated.Value(0));
    });
  colors && av[0].setValue(1);
  return av;
};

const AnimatedColorView = ({
  duration = 1000,
  colors = [],
  loop = false,
  children,
  ...props
}: AnimatedColorViewType) => {
  const [animatedValue] = useState(createValue(colors));

  useEffect(() => {
    let interval: any = null;

    if (loop) {
      let i = 0 + 1;
      interval = setInterval(() => {
        animatedValue.map((item, index) => {
          if (i === index) {
            Animated.timing(item, {
              toValue: 1,
              duration,
              useNativeDriver: true,
            }).start();
          } else {
            Animated.timing(item, {
              toValue: 0,
              duration,
              useNativeDriver: true,
            }).start();
          }
        });
        i = i + 1;
        if (i === colors.length) {
          i = 0;
        }
      }, duration);
    }

    return () => {
      if (interval) {
        clearInterval(interval);
      }
    };
  }, [animatedValue, colors.length, duration, loop]);

  return (
    <View {...props}>
      {colors.map((item, index) => {
        const opacity = animatedValue[index];
        return (
          <Animated.View
            style={[StyleSheet.absoluteFill, {backgroundColor: item, opacity}]}
          />
        );
      })}
      {children}
    </View>
  );
};

export default AnimatedColorView;
```

**Comment by aswincheriyala** [comment]
Added clearInterval for the loop
